### ISSUE TITLE
Omise payment method not show in checkout page

### ISSUE THREAD

**Issue by ghost** [omise/omise-eccube#1]
I've already installed Omise plugin in ec-cube admin and filled public key and secret key out in plugin-settings form, so when I would like to checkout and pick payment method, Omise is not in list of payment. 

what I should do more ?

<img width="1088" alt="screen shot 2559-01-31 at 12 40 04 am" src="https://cloud.githubusercontent.com/assets/16976729/12697334/5023bbaa-c7b3-11e5-9f3d-eda1ca36c089.png">

This is payment method config

<img width="1087" alt="screen shot 2559-01-31 at 12 50 47 am" src="https://cloud.githubusercontent.com/assets/16976729/12697410/dd0c6ee4-c7b4-11e5-9ac2-8b7dd85be8fc.png">

<img width="1092" alt="screen shot 2559-01-31 at 12 40 25 am" src="https://cloud.githubusercontent.com/assets/16976729/12697337/5a99135a-c7b3-11e5-8183-e89c2b3348a1.png">

**Comment by adnaoki** [comment]
Please check the following.
1, 
http://[ECCUBE ADMIN DIR]/ownersstore/
Please enable "To enable" check box.

2, 
http://[ECCUBE ADMIN DIR]/basis/delivery.php
Please edit delivery method and enable "クレジットカード" check box.

**Comment by ghost** [comment]
thanks a lot, so today we have a new problem. I filled public key and secret key out in plugin-settings form but system has error.

![screen shot 2559-02-01 at 11 24 12 am](https://cloud.githubusercontent.com/assets/16976729/12709158/7335dd3e-c8db-11e5-8c5f-7510f2a84398.png)

and then when I would like to checkout cart, payment method list was error.

![screen shot 2559-02-01 at 11 51 47 am](https://cloud.githubusercontent.com/assets/16976729/12709069/84d2bda6-c8da-11e5-8641-22ef6500b24e.png)

**Comment by adnaoki** [comment]
Thank you. Could you tell me php and mysql(postgresql) virsion?

**Comment by ghost** [comment]
My php version is 5.5.9 and mysql version is 5.5.41.

**Comment by adnaoki** [comment]
Thank you.I'll try.

**Comment by adnaoki** [comment]
I'm Sorry, I can not be error.
Would you please show me error log?

[ECCUBE_REAL_DIR]/data/logs/error.log

**Comment by ghost** [comment]
[/eccube-2.13.3/html/shopping/payment.php] Fatal error(E_ERROR): Call to undefined function curl_init() on [/var/www/html/eccube-2.13.3/data/downloads/plugin/OmisePaymentGateway/omise-php/lib/omise/res/OmiseApiResource.php(140)] from 172.17.8.1
customer_id = 1

I will also try to fix it.

**Comment by adnaoki** [comment]
Thank you for your confirmation.
Please contact me if there are other problems.

**Comment by snkrheadz** [comment]
Thanks naoki-san for your kindly help :)

**Comment by ghost** [comment]
@adnaoki thanks a lot, now we can used your plugin.
