### ISSUE TITLE
rearrange Omise button position

### ISSUE THREAD

**Issue by ghost** [omise/omise-eccube#2]
can you rearrange Omise button to payment method list because we think Omise is belong to payment method not delivery method.

![omise designation of such payment method delivery time](https://cloud.githubusercontent.com/assets/16976729/12713689/aca71c8c-c902-11e5-956f-c3cc06b87bc6.png)

**Comment by adnaoki** [comment]
I'm sorry. I revised it.
https://github.com/omise/omise-eccube/blob/develop/v2/OmisePaymentGateway.tar.gz

Please update from the management screen.
But ECCUBE2.13.3 or less there is a bug in the update does not work .
http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=15315&forum=9&post_id=69412#forumpost69412
If you are using ECCUBE2.13.3 or less Please re- install .

**Comment by ghost** [comment]
hi @adnaoki 
your latest commit made plug-in cannot be installed. I know it because I reverted to last commit and plug-in was installed successful.

**Comment by adnaoki** [comment]
It's my fault.
I was put gzip in the repository. That caused the problem.

I latest commit remove OmisePaymentGateway.tar.gz.
I think that you can install .

**Comment by ghost** [comment]
thanks @adnaoki, this issue is solved.
