### ISSUE TITLE
plug-in not charge into omise dashbard when checkout cart is done.

### ISSUE THREAD

**Issue by ghost** [omise/omise-eccube#3]
hi @adnaoki 

I tried to checkout cart by Omise payment gateway and after complete checkout process and then I was going to my Omise Dashboard, charge transaction was not found.

I tested on eccube version 2.13.3 and latest omise-eccube plug-in.

![screen shot 2559-02-12 at 1 50 11 pm](https://cloud.githubusercontent.com/assets/16976729/13000669/a3653588-d18f-11e5-9aaa-5a18ade419a6.png)

**Comment by guzzilar** [comment]
@adnaoki oh! wait, maybe it's because our fault. let us check it again.

Sorry to ping you :sweat_smile:

**Comment by ghost** [comment]
@adnaoki I'm really sorry, my mistake.
